[manifest]
version = "1.0.0"
dump_lua = true
priority = -11

# =========================
# Intercept cash-out to trigger Mysterious Rift
# =========================

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = 'G.STATE = G.STATES.SHOP'
position = 'at'
match_indent = true
payload = '''
if G.GAME.Burger and G.GAME.Burger > 0 then
    G.GAME.Burger = G.GAME.Burger - 1
    G.STATE = G.STATES.BLIND_SELECT
else
    G.GAME.ForcedFail = false
    G.GAME.ForcedFailTriggered = false
    
    -- 1 in 10 chance (10%) to trigger the Mysterious Rift
    if math.random(1, 10) == 6 then
        G.STATE = 6942067
        G.FUNCS.overlay_mysterious_rift()
    else
        G.STATE = G.STATES.SHOP
    end
end
'''